import { Metadata } from "next";
import { PropsWithChildren } from "react";
import { AuthedLayout } from "./authed-layout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function Layout({ children }: PropsWithChildren) {
  const Layout = AuthedLayout;
  return <Layout>{children}</Layout>;
}
